### ISSUE TITLE
Contrast for dark konsole themes not great.

### ISSUE THREAD

**Issue by andyDoucette** [yudax42/askai#3]
This tool is amazing!  Thanks so much for writing it.

One thing, for dark konsole backgrounds it's hard to see the answer.

![Screenshot_20221208_101118](https://user-images.githubusercontent.com/19576950/206346953-2e3debe2-c631-41f2-b32f-bba1eb33a1a6.png)

Possible solutions:
1. Can the colors be overridden by environmental variable or config file or something or maybe we can have a --colorTheme (dark|light) option?  
1. Another option is to write the answer as regular text and the question as colored text.  Most of the terminal colors are legible on light or dark backgrounds  The konsole will color regular text per the user's settings (so there is sufficient contrast).

If  had to pick one, I guess it would be number 2, as it puts more control in the user's hands without adding much work for you.

**Comment by yudax42** [comment]
Hi @andyDoucette, for now I've changed the answer color to white. I will add more control over color customization in the future.

**Comment by andyDoucette** [comment]
Thanks so much. :)

**Comment by andyDoucette** [comment]
Good day.  I tried the new version, and while it's easier to read the response (success!), it's now difficult to tell the difference between the question and the response.  Can the question be in a color like cyan or green?  Those are readable on both white and black backgrounds.

Another thing that will help is to put an extra '\n' at the end of each output by the chat bot, so that question and answer are paired together, and there's a little space between the question and answer pairs.

I'm impressed by your responsiveness so far.  I hope my requests aren't getting annoying.  ChatGPT is just super cool and it's so great to have command line access to it - I'm just  trying to help us get to a polished tool and this seems like a high bang-for-buck tweak.  Thanks so much for your help! :)

**Comment by andyDoucette** [comment]
Oh, and it looks like you changed the reply text to white.  That will be good for me with a black console, but anyone who has a light console will have the same problem.  I think it might be better to set the reply text color to uncolored (the default), so their console settings will have control over the color.  That way it can be white for me and black for someone else as they desire.  Only the prompt needs to be colored so it stands out differently than the rest, IMHO.

**Comment by yudax42** [comment]
Hi @andyDoucette , thank you for reporting this issue. I appreciate your feedback. I have updated the CLI to display the chatGPT response as markdown, which will ensure that it is well-formatted. I have also changed the default color to the default terminal color. To try out these changes, please upgrade to the latest version of the CLI. Thank you!

**Comment by yudax42** [comment]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/75418209/206876762-79828a32-da79-4bf2-ac83-bfbfe71dde75.png">

**Comment by yudax42** [comment]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/75418209/206876825-5ffb94e9-2ccf-4355-bde6-74fe14f64f4e.png">

**Comment by andyDoucette** [comment]
Wow, that's beautiful! :)  Cudos!
