### ISSUE TITLE
ChatGPT failed to refresh auth token. Error: 403 Forbidden

### ISSUE THREAD

**Issue by andyDoucette** [yudax42/askai#5]
When I use `askai login` and enter my `__Secure-next-auth.session-token`, askai responds with `Successfully logged in!`, yet when I try to do `askai live` I get `ChatGPT failed to refresh auth token. Error: 403 Forbidden`.  This just happened a couple days ago.

Curiously, around the same time I noticed that ChatGPT shows a cloudflare (if I recall) splash screen on load now.  That may or may not have something to do with the issue.

If this is a game of cat and mouse I hope we can find just the right sized hole in their defenses to slip through. 😂

**Comment by yudax42** [comment]
Hi @andyDoucette, it appears that the recent Cloudflare change was related to the issue you experienced. haha working with the private API is very unstable, I hope that the official API will be released soon so will switch to it. The issue should now be fixed, but please make sure to update your CLI and refer to the readme for information on the new login process, which requires both a chatgpt token and a Cloudflare clearance token now. Thank you for your patience.

**Comment by andyDoucette** [comment]
Thanks so much!  Will do.  Might be a couple days as my desktop is down for
maintenance.
